### ISSUE TITLE
Issue on page /topics/3_tuning/logging.html

### ISSUE THREAD

**Issue by AndreaKarlova** [comp0190/lectures#1]
I suggest adding more details on handlers and formatting the log string. These are both very useful tools,  see e.g. https://www.datadoghq.com/blog/python-logging-best-practices/#centralize-and-analyze-your-python-logs. Another useful tool which may be worthy to mention is logging module from absail package: https://abseil.io/docs/python/guides/logging
abseil is google open-sourced library used in TensorFlow with the logging module reasonably smoothly built upon the standard python logging module, its fast to use tool.

**Comment by ktmai** [comment]
Thanks for the suggestions - I've added some more detail to the pages. Let me know if you think more detail would be useful!
